version: '3' 
services:
  docker-DL-cpu:
    image: floydhub/dl-docker:cpu
    build:
      context: ./Dockerfile.cpu
    container_name: docker-DL-cpu
    environment:
      - PASSWORD=${JUPYTER_PASSWORD}
    ports:
      - 16006:6006
      - 18888:8888
    env_file:
      - ./docker-DL.env
    volumes:
      - ./data:/data
      - ./notebook:/notebook
#  docker-DL-gpu:
#    image: floydhub/dl-docker:gpu
#    build:
#      context: ./Dockerfile.gpu
#    container_name: docker-DL-cpu
#    environment:
#      - PASSWORD=${JUPYTER_PASSWORD}
#    ports:
#      - 16006:6006
#      - 18888:8888
#    env_file:
#      - ./docker-DL.env
#    volumes:
#      - ./data:/data
#      - ./notebook:/notebook
